test:
  <<: *default
  # Credentials for REST APIs
  client_id: ${PAYPAL_ID}
  client_secret: ${PAYPAL_SECRET}
  client_id: ARH3iOHB8I5OiBqGIo22nky0Nzh9_QgDWSUC_SLfmkPFo_PwMTRoFsRLixXo2XRGC0Uxi3bw1MhSW9KL
  client_secret: EA9Gbp6x5AIlzqn9tdYuu1rsnU-coptK3a3T5M9thU7TPhHSAZe170WC-QTqC2RuJRzBcsgNUxD44Dye

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  #app_id: APP-80W284485P519543T
  #username: jb-us-seller_api1.paypal.com
  #password: WX4WTU3S8MY44S7F
  #signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  #sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  client_id: ${PAYPAL_ID}
  client_secret: ${PAYPAL_SECRET}
  mode: sandbox
